### ISSUE TITLE
[BUG] Inconsistent Callout Icon Text Spacing

### ISSUE THREAD

**Issue by Guanine** [minheeyoon/Dawn#1]
Thank you so much for sharing this superb theme. Your theme is so perfect and beautiful I deleted 99% of my custom CSS. So I feel terrible nitpicking, but as you can see from the screengrab, the spacing between the callout icon and the text is inconsistent. Thanks again for sharing your beautiful theme and your impeccable taste with the rest of us.

**Comment by ds-package** [comment]
Hello! First of all, thank you for letting me know and for your kind words. I checked the information you provided and tried to make some adjustments, but I couldn't find any major issues on my end (please refer to Image 1!). If there are other problems you are referring to, please let me know in more detail!

<img width="999" alt="etc img" src="https://user-images.githubusercontent.com/43980992/232246513-b88286d5-9499-4ee4-9ee1-50843780fabb.png">

Also, thanks to your report, I was able to take a closer look at the Callout icon, and as a result, I have fixed the issue where the icon was slightly lower than the text (please refer to Image 2!). Thank you!

<img width="999" alt="etc img2" src="https://user-images.githubusercontent.com/43980992/232246915-dba35e6c-f7f4-4c9d-9bab-88c87150c943.png">

I've also fixed some minor visual issues through updates, so please make sure to check them out! 
Have a great day and thank you so much.

**Comment by Guanine** [comment]
Thank you so much for looking into this and for the quick update!
I made a fresh new vault and tested it with the updated theme. 😅 But unfortunately, I am still seeing the same issue. Maybe this is a platform-specific issue? Only on Mac? Anyway, it's not a big deal. I still love the theme so much, and I got used to the way the callouts look. 

Here is a screen recording 
Unlisted YouTube video.
https://youtu.be/ERMj67N1QC0

macOS Ventura 13.3.1
Obsidian v1.2.2 (Installer version: v1.1.9)

**Comment by godswork** [comment]
Same
